language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer require --dev squizlabs/php_codesniffer:2.*
  - composer require drupal/coder:^8.2
  - composer install
  - vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer

script:
  - vendor/bin/phpcs --standard=vendor/drupal/coder/coder_sniffer/Drupal --extensions=php,module,inc,install,test,profile,theme,js,css,info,txt ./test/my_module/